const codes = 
{
    acad:"Acadia National Park",
    npsa:"American Samoa",
    arch:"Arches",
    badl:"Badlands",
    bibe:"Big Bend",
    bisc:"Biscayne Bay",
    blca:"Black Canyon of the Gunnison",
    brca:"Bryce Canyon",
    cany:"Canyonlands",
    care:"Capitol Reef",
    cave:"Carlsbad Caverns",
    chis:"Channel Islands",
    cong:"Congaree",
    crla:"Crater Lake",
    cuva:"Cuyahoga Valley",
    deva:"Death Valley",
    dena:"Denali",
    drto:"Dry Tortugas",
    ever:"Everglades",
    gaar:"Gates of the Arctic",
    jeff:"Gateway Arch",
    glac:"Glacier",
    glba:"Glacier Bay",
    grca:"Grand Canyon",
    grte:"Grand Teton",
    grba:"Great Basin",
    grsa:"Great Sand Dunes",
    grsm:"Great Smoky Mountains",
    gumo:"Guadalupe Mountains",
    hale:"Haleakala",
    havo:"Hawaii Volcanoes",
    hosp:"Hot Springs",
    indu:"Indiana Dunes",
    isro:"Isle Royale",
    jotr:"Joshua Tree",
    katm:"Katmai",
    kefj:"Kenai Fjords",
    seki:"Kings Canyon",
    kova:"Kobuk Valley",
    lacl:"Lake Clark",
    lavo:"Lassen Volcanic",
    maca:"Mammoth Cave",
    meve:"Mesa Verde",
    mora:"Mount Rainier",
    noca:"North Cascades",
    olym:"Olympic",
    pefo:"Petrified Forest",
    pinn:"Pinnacles",
    redw:"Redwood",
    romo:"Rocky Mountain",
    sagu:"Saguaro",
    seki:"Sequoia",
    shen:"Shenandoah",
    thro:"Theodore Roosevelt",
    viis:"Virgin Islands",
    voya:"Voyageurs",
    whsa:"White Sands",
    wica:"Wind Cave",
    wrst:"Wrangell-St. Elias",
    yell:"Yellowstone",
    yose:"Yosemite",
    zion:"Zion"
}